### ISSUE TITLE
Is it possible to know what part of the xml is invalid ?

### ISSUE THREAD

**Issue by loresclement** [stafyniaksacha/facturx#2]
Hello !

I'm building my xml based on an existing facturX invoice. I can't really find the docs so it's hard 
Is it easy to implement the feature that indicates where the xml is malformed ? 

I get the error : 

"npx @stafyniaksacha/facturx generate --pdf invoice.pdf --xml xmlGENERATED.xml --output output.pdf

 ERROR  Invalid XML format (facturx - en16931)                        13:18:05

  at generate (node_modules/@stafyniaksacha/facturx/dist/index.mjs:264:11)
  at async Object.run (node_modules/@stafyniaksacha/facturx/dist/chunks/generate.mjs:56:21)
  at async runCommand (node_modules/citty/dist/index.mjs:316:16)
  at async runCommand (node_modules/citty/dist/index.mjs:307:11)
  at async runMain (node_modules/citty/dist/index.mjs:445:7) 

 ERROR  Invalid XML format (facturx - en16931)"

Which is fine, but I have no information about why the format is invalid

Thank you !

**Comment by stafyniaksacha** [comment]
Hello @loresclement !

> I'm building my xml based on an existing facturX invoice. I can't really find the docs so it's hard

Yes, unfortunately, the only thing we have is XSD files definitions, and a XLSM file with Excel macros.

> Is it easy to implement the feature that indicates where the xml is malformed ?

I've made it working in latest update `v0.3.0`: 

CLI usage: 

`npx @stafyniaksacha/facturx check xmlGENERATED.xml` will output errors like: 

```
Invalid XML format (facturx - minimum):
Element '{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}ApplicableTradeTax': This element is not expected. Expected is ( {urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}SpecifiedTradeSettlementHeaderMonetarySummation ).
```

Programmatic usage:

```ts
import { check } from '@stafyniaksacha/facturx'

const xml = `<?xml version="1.0" encoding="UTF-8"?>...`

try {
  const { valid, errors } = await check(xml)
  console.log({ valid, errors })
}
catch (error) {
  console.log("error processing xml", error)
}
```

There are still some validation errors that occur only on `https://services.fnfe-mpe.org/` that I'm trying to catch.
